### ISSUE TITLE
Rename "source" to "type", "spec" or "specification"

### ISSUE THREAD

**Issue by altavir** [waltz-controls/rfc#2]
`Source`  is confusing because I would think that it marks the source device.

**Comment by altavir** [comment]
Target seems to be useless because the source designates specification and not the actual source.

**Comment by Ingvord** [comment]
Idea here is to indicate a kind of a "place" from where a message originates IMHO `source` better fits for this purpose rather than `type`, another alternative that I like is `upstream`, but this is immediately triggers association with git forks... (maybe only my own feeling though)

**Comment by altavir** [comment]
The problem is that we have the source system and the source device, so it is confusing. Your source de-facto designates the message format, not its origin.

**Comment by Ingvord** [comment]
> The problem is that we have the source system and the source device, so it is confusing.

Completely agree

> Your source de-facto designates the message format, not its origin.

Not really. Message format is defined by this RFC. `source` is really a place of origin.

Maybe call it `origin`?

**Comment by altavir** [comment]
`origin` is OK

**Comment by Ingvord** [comment]
Done in 7c21006
