### ISSUE TITLE
Specify what does "parent" mean

### ISSUE THREAD

**Issue by altavir** [waltz-controls/rfc#3]
I am not sure what is the purpose of the field.

**Comment by Ingvord** [comment]
`parent` - `id` of the message result of which produces this message e.g. read Tango attribute request (id=1234) -> read Tango attribute response (id=1235, parent=1234)

**Comment by altavir** [comment]
It is not clear who handles the ids and how we ensure iniquity. If the id is generated by TANGO, it should be the part of the payload.

**Comment by Ingvord** [comment]
`id` generated by message creator, in our case that will be connectors e.g. Tango  connector not Tango itself. As first approximation I suggest to use timestamps for that... in the future that will be hash values (aka blockchain)

**Comment by Ingvord** [comment]
Close via 7c739e9
